version: '3'

services:
  myredis:
    image: 'redis:alpine'
    container_name: myredis
    ports: 
      - 6379:6379
  mypostgres:
    image: 'postgres:alpine'
    container_name: mypostgres
    environment: 
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5432:5432
  myapi:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=mypostgres
      - REDIS_PORT=6379
      - REDIS_HOST=myredis
    ports:
      - 5000:5000
    command: sh -c "sleep 5 && node /usr/src/server-api/app.js"