version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always

  front:
    build:
      dockerfile: Dockerfile.dev
      context: ./my-app
    container_name: front
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "/front/node_modules"
      - "./my-app:/front"
