version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 5000:5000
    container_name: backend

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 80:80
    container_name: frontend
