apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-deployment
  labels:
    type: postgres

spec:
  template:
    metadata:
      name: pg
      labels:
        type: pod-pg

    spec:
      containers:
        - name: postgres-pod
          image: postgres:alpine
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: mypostgres

  replicas: 2
  selector:
    matchLabels:
      type: pod-pg
