apiVersion: v1
kind: Pod

metadata:
  name: frontend-pod
  labels:
    name: app

spec:
  containers:
    - name: frontend
      image: frontend-image
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
