version: "3"

services:
  myredis:
    image: redis
    container_name: myredis

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    environment:
      - REDIS_HOST=myredis
      - REDIS_PORT=6379

    ports:
      - 3000:3000

    volumes:
      - "/app/node_modules"
      - "./backend:/app"
