version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: backend
    volumes:
      - "/usr/src/my-app/backend/node_modules"
      - "./backend:/usr/src/my-app/backend"

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "/usr/src/my-app/frontend/node_modules"
      - "./frontend:/usr/src/my-app/frontend"
